'use client'
import type { Schema } from '@/data-schema'
import { generateClient } from 'aws-amplify/api'
import type { Metadata } from 'next'
import { useCallback, useEffect } from 'react'
import { Amplify } from 'aws-amplify'
import './globals.css'
import awsconfig from '../amplify_outputs.json'

Amplify.configure(awsconfig)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = generateClient<Schema>()

  const createTodo = useCallback(async () => {
    await client.models.Todo.create({
      content: 'Test',
    })
  }, [client])

  useEffect(() => {
    createTodo()
  }, [createTodo])

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
